### ISSUE TITLE
Cannot confirm default if waitForNewLine is false

### ISSUE THREAD

**Issue by DRSchlaubi** [frencojobs/interact#6]
If you have a `Confirm` with `waitForNewLine: true`  the default value does pretty much nothing. It preselects the default, but you cannot hit enter to confirm it, you need to manually press y/n

**Comment by frencojobs** [comment]
It is intentional that you have to choose with y/n if `waitForNewLine` is not true. I'm pretty sure you're missing `waitForNewLine` together with the default value. Can you check again? Adding it worked out for me.

![image](https://user-images.githubusercontent.com/17830687/132080612-f08ba23f-1512-4872-9a34-468040708da1.png)

Otherwise, it could be a bug. Let me know which versions of interact & dart you're using. Also which shell are you on? Thanks.

**Comment by DRSchlaubi** [comment]
yes i am using it together with defaultValue, but if I hit enter nothing happens.
The option is called waitForNewLine so waitForNewLine: false sounds like if you pressed `y` you don't wait for a new line to confirm that
but you don't expect it to disable enter at all

**Comment by frencojobs** [comment]
Huh, I'm not understanding you correctly. Are you using `waitForNewLine` with the value of `true` or `false`? 

The rule of thumb would be,

1. Enter key only works with `waitForNewLine`. 
2. Setting `defaultValue` only pre-selects the value, it does nothing else.

Is something going wrong according to these rules?

**Comment by DRSchlaubi** [comment]
> Huh, I'm not understanding you correctly. Are you using waitForNewLine with the value of true or false?

false, did the title wrong sorry

> Enter key only works with waitForNewLine.
as I said, that is not what the name suggests

> Setting defaultValue only pre-selects the value, it does nothing else.
Exactly, it preselects it, but what's the point of a preselection if you cannot confirm it?

**Comment by frencojobs** [comment]
Ok got it. Seems like you also did the issue description wrong.
> If you have a Confirm with `waitForNewLine: true`

Still, I'm not sure what is the issue.
> Enter key only works with waitForNewLine.
as I said, that is not what the name suggests

That's exactly what the name suggests, it waits for <kbd>enter</kbd> key aka return, carriage, new line whatever.

> Setting defaultValue only pre-selects the value, it does nothing else.
Exactly, it preselects it, but what's the point of a preselection if you cannot confirm it?

Use `waitForNewLine: true` so that the user can confirm the preselection with <kbd>enter</kbd> key.

If you're trying to choose a value (which using `waitForNewLine: false` suggests) without letting the user make a choice, you can't. It sounds wrong. Why would you show a prompt that a user can't make a decision to?

**Comment by frencojobs** [comment]
Ok sorry, I now see the point. You want to enable `waitForNewLine` to be `true` when `defaultValue` is set, right? Sure, that sounds much rational. Will add that soon. Thanks.

**Comment by DRSchlaubi** [comment]
I was explaining it wrong in the beginning
if you have waitForNewLine: false
and a default set


Then the user of the CLI using interact might think. Oh there is a highlighted Y there and presses enter to try to confirm it, and then get's confused because nothing happens

if you have something like `You want to confirm (Y/n):` and you want to have enter as a confirm, but still just n (without enter) to decline
